### PR TITLE
Support for query templating (for example to use git hash as table postfix)

### PR DESCRIPTION
**Pull request by gaborvolczer**
@nbali I know you will not like this solution but I'm not sure how to do this properly so I pushed this working solution and we can iterate on it :) 

I wanted to implement a general solution insted of a Trivago specific one. Maybe we should accept a map in the arguments with any additional parameters as key/value instead of a String gitHash? It would be more general ... and maybe an overkill.

About the implementation: JarvisContext represented a json object and it's messed up by this PR but I'm not sure what would be the best solution. Create a wrapper with the extra field? Or we should not even put the hash into the context but get it directly from the environment?

---
This change is [Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)

### CODE REVIEW

**Review by nbali — CHANGES_REQUESTED** [review]
"Maybe we should accept a map in the arguments with any additional parameters as key/value instead of a String gitHash"

I actually like this, we should have the parameter map from the context json, and the insert/override any key from parameters from the launch of the app during the context loading phase, we should only ignore jarvis specific values like "config"

SimpleCommandLinePropertySource could be used for this

> Reviewed 1 of 2 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50#-:-MzWvmUODCuJJy3zmzIu:b-d4d5ho)* status: all files reviewed, 7 unresolved discussions (waiting on @gaborvolczer)

___
*[src/main/java/ai/aliz/jarvis/context/JarvisContext.java, line 39 at r2](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzWsl2G20J8SebKOgoa:-MzWsl2G20J8SebKOgob:binzv3) ([raw file](https://github.com/aliz-ai/jarvis/blob/049f3062069bb8d57efeb3b69670632b7e5c7fb0/src/main/java/ai/aliz/jarvis/context/JarvisContext.java#L39)):*
> ```Java
>     private final Map<String, String> parameters;
>     
>     private String gitHash="";
> ```

default should be null or optional.empty

also @wither 
___
*[src/main/java/ai/aliz/jarvis/context/JarvisContext.java, line 50 at r2](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzWspy2AspTGO3Y81EN:-MzWspy2AspTGO3Y81EO:b-2l6p3q) ([raw file](https://github.com/aliz-ai/jarvis/blob/049f3062069bb8d57efeb3b69670632b7e5c7fb0/src/main/java/ai/aliz/jarvis/context/JarvisContext.java#L50)):*
> ```Java
>     public void setGitHash(String gitHash){
>         this.gitHash=gitHash;
>     }
> ```

why not @setter?
___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 53 at r2](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzWuy_0B_-Y-3eNGGMv:-MzWuy_0B_-Y-3eNGGMw:bda2ldo) ([raw file](https://github.com/aliz-ai/jarvis/blob/049f3062069bb8d57efeb3b69670632b7e5c7fb0/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L53)):*
> ```Java
>     
>     @SneakyThrows
>     private Set<JarvisContext> parseContexts(String contextPath) {
> ```

you could just pass in the environment as a parameter :)
___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 56 at r2](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzWvcOA6PYQoMVakvf3:-MzWvcOA6PYQoMVakvf4:bnucuri) ([raw file](https://github.com/aliz-ai/jarvis/blob/38e2383dcb769f4498dffdf4269b99d550503dfc/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L56)):*
> ```Java
>         Set<JarvisContext> contexts = objectMapper.readValue(Files.asCharSource(new File(contextPath), StandardCharsets.UTF_8).read(), typeReference);
>         log.info("Jarvis context loaded: {}", contexts);
>         validateContexts(contexts);
> ```

why did u remove it
___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 62 at r2](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzWv6Tz66HmguHb7LXo:-MzWv6Tz66HmguHb7LXp:b8axa8a) ([raw file](https://github.com/aliz-ai/jarvis/blob/049f3062069bb8d57efeb3b69670632b7e5c7fb0/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L62)):*
> ```Java
>         String gitHash = environment.getProperty(GIT_HASH);
>         if (!Strings.isNullOrEmpty(gitHash)){
>             contexts.forEach(c->c.setGitHash(gitHash));
> ```

lombok.wither would look so much more natural for this
___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 62 at r2](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzWvTxp18ZRqX675XXA:-MzWvTxp18ZRqX675XXB:b-mmrqeq) ([raw file](https://github.com/aliz-ai/jarvis/blob/049f3062069bb8d57efeb3b69670632b7e5c7fb0/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L62)):*
> ```Java
>         String gitHash = environment.getProperty(GIT_HASH);
>         if (!Strings.isNullOrEmpty(gitHash)){
>             contexts.forEach(c->c.setGitHash(gitHash));
> ```

if you plan to include in the parameters anyway, why don't you add it now?
___
*[src/main/java/ai/aliz/jarvis/db/BigQueryExecutor.java, line 117 at r2](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzWt9Px9dIv7MdyeFI9:-MzWt9Px9dIv7MdyeFIA:b74bybp) ([raw file](https://github.com/aliz-ai/jarvis/blob/049f3062069bb8d57efeb3b69670632b7e5c7fb0/src/main/java/ai/aliz/jarvis/db/BigQueryExecutor.java#L117)):*
> ```Java
>     public TableResult executeQueryAndGetResult(String query, JarvisContext context) {
>         Map<String, String> parameters = context.getParameters();
>         parameters.put(GIT_HASH, context.getGitHash()==null?"":"_"+context.getGitHash());
> ```

"_" + git hash isn't git hash anymore, it's a table suffix.... I get that you want to use "_" before the git hash but it's the responsibility of the script writer to include that underscore... without that it can be even used as a prefix...


also definitely don't mess around with a map from another pojo, make a copy and modify that

**Review by nbali — COMMENTED** [review]
or just replace 'CommandLineRunner' with 'ApplicationRunner' and you get 'ApplicationArguments'

> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50#-:-MzX73HL57TCRWlTSXp4:bo3z2ep)* status: all files reviewed, 7 unresolved discussions (waiting on @gaborvolczer)

**Review by nbali — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: all files reviewed, 5 unresolved discussions (waiting on @gaborvolczer)

___
*[src/main/java/ai/aliz/jarvis/context/JarvisContext.java, line 27 at r6](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzugbQq5pUBTXM7hZVS:-MzugbQq5pUBTXM7hZVT:b-5xwlr1) ([raw file](https://github.com/aliz-ai/jarvis/blob/29c857dcbfd841a59e333d0a5215edbe6e325e3c/src/main/java/ai/aliz/jarvis/context/JarvisContext.java#L27)):*
> ```Java
> @ToString
> @EqualsAndHashCode
> @AllArgsConstructor
> ```

  I think this is `@Value` now
___
*[src/main/java/ai/aliz/jarvis/context/JarvisContext.java, line 40 at r6](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzugSgK6sm_XZSSSpif:-MzugSgK6sm_XZSSSpig:b-ymapgu) ([raw file](https://github.com/aliz-ai/jarvis/blob/29c857dcbfd841a59e333d0a5215edbe6e325e3c/src/main/java/ai/aliz/jarvis/context/JarvisContext.java#L40)):*
> ```Java
>     
>     @JsonProperty(PARAMETERS)
>     private Map<String, String> parameters;
> ```

fyi could ahve been final too
___
*[src/main/java/ai/aliz/jarvis/service/assertaction/BqAssertor.java, line 149 at r6](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzugoGg8kBgrTPQ-LXZ:-MzugoGg8kBgrTPQ-LX_:b4h2yle) ([raw file](https://github.com/aliz-ai/jarvis/blob/29c857dcbfd841a59e333d0a5215edbe6e325e3c/src/main/java/ai/aliz/jarvis/service/assertaction/BqAssertor.java#L149)):*
> ```Java
>             dataset = datasetNamePrefix + dataset;
>         }
>         String table = assertActionConfig.getProperties().get("table")+context.getParameter(TABLE_POSTFIX);
> ```

(formatter)
___
*[src/main/java/ai/aliz/jarvis/util/JarvisConstants.java, line 27 at r6](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzugwOH1hH1iKTO3Dx0:-MzugwOH1hH1iKTO3Dx1:b3kqx) ([raw file](https://github.com/aliz-ai/jarvis/blob/29c857dcbfd841a59e333d0a5215edbe6e325e3c/src/main/java/ai/aliz/jarvis/util/JarvisConstants.java#L27)):*
> ```Java
>     String CONTEXT = "context";
>     
>     /* TODO doc */
> ```

.
___
*[src/main/java/ai/aliz/jarvis/util/JarvisConstants.java, line 32 at r6](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzugxsuCrwSYHTEDtSQ:-MzugxsuCrwSYHTEDtSR:b6zy6i) ([raw file](https://github.com/aliz-ai/jarvis/blob/29c857dcbfd841a59e333d0a5215edbe6e325e3c/src/main/java/ai/aliz/jarvis/util/JarvisConstants.java#L32)):*
> ```Java
>     /* Parameters excluded in this lists will be handled as "additional parameters" and will be inserted/override in the environment parameter map*/
>     Set<String> BASE_PARAMETERS = Stream.of(CONTEXT, CONFIG)
>                                         .collect(Collectors.toSet());
> ```

should be immutable -> for example `ImmutableSet..f(CONTEXT, CONFIG)` or `ImmutableSet.toImmutableSet()` 
___
*[src/main/java/ai/aliz/jarvis/util/JarvisConstants.java, line 35 at r6](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzuhNKW8s90QFSuJ-ib:-MzuhNKW8s90QFSuJ-ic:bb7qx7k) ([raw file](https://github.com/aliz-ai/jarvis/blob/29c857dcbfd841a59e333d0a5215edbe6e325e3c/src/main/java/ai/aliz/jarvis/util/JarvisConstants.java#L35)):*
> ```Java
>     
>     /* If a jarvis test is triggered by each commit we need to use a tablePostfix to resolve conflicting BQ tables.
>     If the application is added to another repo as a jar and we want to use for example git commit information in the postfix, the easiest was is to pass it as a parameter
> ```

way*
___
*[src/test/java/ai/aliz/jarvis/context/TestJarvisContextLoader.java, line 41 at r6](https://reviewable.io/reviews/aliz-ai/jarvis/50#-Mzuhdl4C2zJHgGU_6NJ:-Mzuhdl4C2zJHgGU_6NK:br2hblz) ([raw file](https://github.com/aliz-ai/jarvis/blob/29c857dcbfd841a59e333d0a5215edbe6e325e3c/src/test/java/ai/aliz/jarvis/context/TestJarvisContextLoader.java#L41)):*
> ```Java
>                                                                  .putParameter(PROJECT, "nora-ambroz-sandbox")
>                                                                  .putParameter(DATASET_NAME_PREFIX, "core_")
>                                                                  .putParameter("stagingDataset", "STAGING");
> ```

I'm not sure I get why the putParameter had to be excluded from the normal build

**Review by nbali — DISMISSED** [review]
> Reviewed 4 of 4 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: all files reviewed, 1 unresolved discussion (waiting on @gaborvolczer)

*[a discussion](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N-Q05oN0euaxaSew5N8:-N-Q05oN0euaxaSew5N9:b-o8nj5b) (no related file):*
fyi there are unused imports now

---
___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 63 at r8](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N-Q-i3405MJ1wEF1_sD:-N-Q-i3405MJ1wEF1_sE:b-ojeya0) ([raw file](https://github.com/aliz-ai/jarvis/blob/774744b69af184ae2969a099e2cccae14202434e/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L63)):*
> ```Java
>         validateContexts(contexts);
>         
>         SimpleCommandLinePropertySource propertySource =(SimpleCommandLinePropertySource) environment.getPropertySources().get(CommandLinePropertySource.COMMAND_LINE_PROPERTY_SOURCE_NAME);
> ```

out of curiosity, what is the difference compared to `environment.getSystemProperties()`?

**Review by nbali — APPROVED** [review]
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: all files reviewed, 1 unresolved discussion (waiting on @gaborvolczer)

**Review by nbali — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: all files reviewed, 2 unresolved discussions (waiting on @gaborvolczer)

*[a discussion](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N-Q3SCSCIPbJV3BoShp:-N-Q3SCSCIPbJV3BoShq:b-crzgvw) (no related file):*
NPE during tests

---

**Review by gaborvolczer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: all files reviewed, 2 unresolved discussions (waiting on @nbali)

*[a discussion](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N-Q3SCSCIPbJV3BoShp:-N-ShlXKCGb3WSdofyKM:b-896fix) (no related file):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

NPE during tests
</blockquote></details>

Done.

---
___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 53 at r2](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzWuy_0B_-Y-3eNGGMv:-MzowZU0Cy_gOxuyAo4s:bwqzcsr) ([raw file](https://github.com/aliz-ai/jarvis/blob/049f3062069bb8d57efeb3b69670632b7e5c7fb0/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L53)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

you could just pass in the environment as a parameter :)
</blockquote></details>

I prefer the methods with less parameter
___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 56 at r2](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzWvcOA6PYQoMVakvf3:-MzovN2C6uUsXxv0nYst:b-896fix) ([raw file](https://github.com/aliz-ai/jarvis/blob/38e2383dcb769f4498dffdf4269b99d550503dfc/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L56)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

why did u remove it
</blockquote></details>

Done.
___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 62 at r2](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzWv6Tz66HmguHb7LXo:-MzovuJR-MexDqw35x8b:b-896fix) ([raw file](https://github.com/aliz-ai/jarvis/blob/049f3062069bb8d57efeb3b69670632b7e5c7fb0/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L62)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

lombok.wither would look so much more natural for this
</blockquote></details>

Done.
___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 63 at r8](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N-Q-i3405MJ1wEF1_sD:-N-ShKJe2RXu9e9AlXyz:br6vfr0) ([raw file](https://github.com/aliz-ai/jarvis/blob/774744b69af184ae2969a099e2cccae14202434e/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L63)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

out of curiosity, what is the difference compared to `environment.getSystemProperties()`?
</blockquote></details>

environment.getSystemProperties() gives a map which contains the whole commandline property as one entry 

___
*[src/main/java/ai/aliz/jarvis/util/JarvisConstants.java, line 27 at r6](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzugwOH1hH1iKTO3Dx0:-N-35fcHD7tjYywtG5aL:b-896fix) ([raw file](https://github.com/aliz-ai/jarvis/blob/29c857dcbfd841a59e333d0a5215edbe6e325e3c/src/main/java/ai/aliz/jarvis/util/JarvisConstants.java#L27)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/main/java/ai/aliz/jarvis/util/JarvisConstants.java, line 32 at r6](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzugxsuCrwSYHTEDtSQ:-MzzHvQD2AKrqB-LweF6:b-896fix) ([raw file](https://github.com/aliz-ai/jarvis/blob/29c857dcbfd841a59e333d0a5215edbe6e325e3c/src/main/java/ai/aliz/jarvis/util/JarvisConstants.java#L32)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

should be immutable -> for example `ImmutableSet..f(CONTEXT, CONFIG)` or `ImmutableSet.toImmutableSet()` 
</blockquote></details>

Done.

**Review by gaborvolczer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @nbali)

___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 65 at r10](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N-Si7DF4YnfWcyKHqen:-N-Si7DF4YnfWcyKHqeo:b74vket) ([raw file](https://github.com/aliz-ai/jarvis/blob/49b0a190ffe9be1f2bb3092e80b6e6ae807cc202/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L65)):*
> ```Java
>         SimpleCommandLinePropertySource propertySource =(SimpleCommandLinePropertySource) environment.getPropertySources().get(CommandLinePropertySource.COMMAND_LINE_PROPERTY_SOURCE_NAME);
>         
>         if (propertySource!=null) {
> ```

@nbali This is an ugly hack to make TestInitActionConfigFactory work.
There is no COMMAND_LINE_PROPERTY_SOURCE_NAME. I gave up to set or mock it in the test. Do you have any idea?

**Review by nbali — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: all files reviewed, 1 unresolved discussion (waiting on @gaborvolczer)

___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 53 at r2](https://reviewable.io/reviews/aliz-ai/jarvis/50#-MzWuy_0B_-Y-3eNGGMv:-N-TEeiE970bOjAbk5KU:b-4c8lqj) ([raw file](https://github.com/aliz-ai/jarvis/blob/049f3062069bb8d57efeb3b69670632b7e5c7fb0/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L53)):*
<details><summary><i>Previously, gaborvolczer wrote…</i></summary><blockquote>

I prefer the methods with less parameter
</blockquote></details>

this was written when even the ConfigutableEnvironment wasn't present, you already did what I wrote there
___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 65 at r10](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N-Si7DF4YnfWcyKHqen:-N-TFlYT6-1TXS92ho74:b-8irqw7) ([raw file](https://github.com/aliz-ai/jarvis/blob/49b0a190ffe9be1f2bb3092e80b6e6ae807cc202/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L65)):*
<details><summary><i>Previously, gaborvolczer wrote…</i></summary><blockquote>

@nbali This is an ugly hack to make TestInitActionConfigFactory work.
There is no COMMAND_LINE_PROPERTY_SOURCE_NAME. I gave up to set or mock it in the test. Do you have any idea?
</blockquote></details>

try injecting+using+mocking org.springframework.boot.ApplicationArguments (https://stackoverflow.com/questions/55868420/how-to-get-command-line-arguments-in-spring-boot)

I would guess injecting that works even if this property source isn't present
___
*[src/test/java/ai/aliz/jarvis/context/TestJarvisContextLoader.java, line 99 at r10](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N-TIhdT8Bt_yN2ZpPu5:-N-TIhdT8Bt_yN2ZpPu6:b6wu1x3) ([raw file](https://github.com/aliz-ai/jarvis/blob/49b0a190ffe9be1f2bb3092e80b6e6ae807cc202/src/test/java/ai/aliz/jarvis/context/TestJarvisContextLoader.java#L99)):*
> ```Java
>         
>         MutablePropertySources mockedMutablePropertySources =  Mockito.mock(MutablePropertySources.class);
>         Mockito.doReturn(mockedPropertySources).when(mockedMutablePropertySources).get(CommandLinePropertySource.COMMAND_LINE_PROPERTY_SOURCE_NAME);
> ```

fyi you can make chains easier with deep stubbing:
https://rieckpil.de/creating-deep-stubs-with-mockito-to-chain-method-stubbing/

**Review by gaborvolczer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: all files reviewed, 1 unresolved discussion (waiting on @nbali)

___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 65 at r10](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N-Si7DF4YnfWcyKHqen:-N-c60Zg8glNpKw0j_dq:bilslte) ([raw file](https://github.com/aliz-ai/jarvis/blob/49b0a190ffe9be1f2bb3092e80b6e6ae807cc202/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L65)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

try injecting+using+mocking org.springframework.boot.ApplicationArguments (https://stackoverflow.com/questions/55868420/how-to-get-command-line-arguments-in-spring-boot)

I would guess injecting that works even if this property source isn't present

</blockquote></details>

I could not make it work in my timebox :) 
___
*[src/test/java/ai/aliz/jarvis/context/TestJarvisContextLoader.java, line 99 at r10](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N-TIhdT8Bt_yN2ZpPu5:-N-c57Rp7GTRoIcihlLm:b-feos1y) ([raw file](https://github.com/aliz-ai/jarvis/blob/49b0a190ffe9be1f2bb3092e80b6e6ae807cc202/src/test/java/ai/aliz/jarvis/context/TestJarvisContextLoader.java#L99)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

fyi you can make chains easier with deep stubbing:
https://rieckpil.de/creating-deep-stubs-with-mockito-to-chain-method-stubbing/
</blockquote></details>

Thx but it would not work in this case. I have Mockito.doReturn instead of Mockito.when in line 99 on purpose. With Mockito.when  (or deep stubbing) I can not "cast" it to SimpleCommandLinePropertySource so I have no getPropertyNames() method.

Let me know if you have a better solution but this was the only way I could solve this.

**Review by nbali — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: all files reviewed, 1 unresolved discussion (waiting on @gaborvolczer)

___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 65 at r10](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N-Si7DF4YnfWcyKHqen:-N-cJ1ce4RLbyfNZrM7p:b-qui1ej) ([raw file](https://github.com/aliz-ai/jarvis/blob/49b0a190ffe9be1f2bb3092e80b6e6ae807cc202/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L65)):*
<details><summary><i>Previously, gaborvolczer wrote…</i></summary><blockquote>

I could not make it work in my timebox :) 
</blockquote></details>

Make what work, ApplicationArguments?
___
*[src/test/java/ai/aliz/jarvis/context/TestJarvisContextLoader.java, line 99 at r10](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N-TIhdT8Bt_yN2ZpPu5:-N-cJLQ35HvTiWQ0ycNN:b-p3v5lb) ([raw file](https://github.com/aliz-ai/jarvis/blob/49b0a190ffe9be1f2bb3092e80b6e6ae807cc202/src/test/java/ai/aliz/jarvis/context/TestJarvisContextLoader.java#L99)):*
<details><summary><i>Previously, gaborvolczer wrote…</i></summary><blockquote>

Thx but it would not work in this case. I have Mockito.doReturn instead of Mockito.when in line 99 on purpose. With Mockito.when  (or deep stubbing) I can not "cast" it to SimpleCommandLinePropertySource so I have no getPropertyNames() method.

Let me know if you have a better solution but this was the only way I could solve this.
</blockquote></details>

mea culpa, true

**Review by nbali — COMMENTED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: all files reviewed, 1 unresolved discussion (waiting on @gaborvolczer)

**Review by nbali — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: all files reviewed, 1 unresolved discussion (waiting on @gaborvolczer)

**Review by gaborvolczer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: all files reviewed, 1 unresolved discussion (waiting on @nbali)

___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 91 at r11](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N00oc115axLzwCn3R9W:-N00oc115axLzwCn3R9X:btyl0g3) ([raw file](https://github.com/aliz-ai/jarvis/blob/dee1cf0c416b56a3f9cc33f0f8ad9f23ded3085c/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L91)):*
> ```Java
>     private String getParameterValue(ApplicationArguments arguments, String name) {
>         // they are environment variables not application arguments, but it could change
>         Preconditions.checkArgument(!BASE_PARAMETERS.contains(name), "Environment variable used as parameter: {}", name);
> ```

We add those as arguments. I remove this precondition and add a filter.

**Review by nbali — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> Dismissed @gaborvolczer from a discussion.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: all files reviewed, 1 unresolved discussion (waiting on @gaborvolczer)

___
*[src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java, line 91 at r11](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N00oc115axLzwCn3R9W:-N02CyP4-Ctl13wFuGZD:bnbzyzt) ([raw file](https://github.com/aliz-ai/jarvis/blob/dee1cf0c416b56a3f9cc33f0f8ad9f23ded3085c/src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java#L91)):*
<details><summary><i>Previously, gaborvolczer wrote…</i></summary><blockquote>

We add those as arguments. I remove this precondition and add a filter. 
</blockquote></details>

as discussed in chat
___
*[src/main/java/ai/aliz/jarvis/util/JarvisUtil.java, line 83 at r13](https://reviewable.io/reviews/aliz-ai/jarvis/50#-N02DUTK2MxsfI-CbNwW:-N02DUTLDE-7LQ8vPn3N:b-yq2j3j) ([raw file](https://github.com/aliz-ai/jarvis/blob/4069d10534713140f9012e7eeb9bd7b000b7c43d/src/main/java/ai/aliz/jarvis/util/JarvisUtil.java#L83)):*
> ```Java
>         }
>         
>         if (MISSING_PLACEHOLDER_REGEX.matcher(result).find()) {
> ```

okay, cleanup is needed, there are two methods for this functionality, I was looking at a different one when we talked, and it's mixed which one is being called (4× vs 5×)

`JarvisUtil.resolvePlaceholders`and `PlaceholderResolver.resolve`

merge them with the same functionality 

(I would prefer moving the "resolve" code to the "resolver" class, I don't like generic utility classes... meanwhile I don't see a reason why the resolver class shouldn't be a static utility class)

**Review by nbali — DISMISSED** [review]
> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaborvolczer)

**Review by nbali — APPROVED** [review]
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaborvolczer)

**Comment by nbali** [comment]
@gaborvolczer auto-merge was on by accident, please review the latest changes

**Comment by gaborvolczer** [comment]
> @gaborvolczer auto-merge was on by accident, please review the latest changes

done

**Pull request merged**
