### PR TITLE
Rename test -> jarvis + cleanup talend packages

### PR DESCRIPTION
**Pull request by gaborvolczer**
In case of TestCase and TestSuit I just added a "Jarvis" prefix instead of replacing "test" because "JarvisTestCase" feels better than "JarvisCase" to me.

Because of this instead of searching for the string "text" I used this regex:
(?=(?<!((?i)J)arvis))(?=(?<!((?i)T)alend))((?i)T)est

(turn match case on)

---
This change is [Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45)

### CODE REVIEW

**Review by nbali — CHANGES_REQUESTED** [review]
> Reviewed 40 of 40 files at r1, 48 of 48 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45)* status: all files reviewed, 3 unresolved discussions (waiting on @gaborvolczer)

___
*[examples/sample_volczi/contexts.json, line 12 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoWD7-4Dan3riP64ov:-MxoWD7-4Dan3riP64ow:bd62cvy) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_volczi/contexts.json#L12)):*
> ```JSON
>   {
>     "id": "local",
>     "contextType": "LocalContext",
> ```

fyi this something I really wanna get rid of soon :D I mean the files should be all referenced as relative paths, and the parameter provided (the context.json or the suite.json) to the app should determine the "repositoryRoot"

so there would be no "local" here

and "queryPath" would be "volcziTest/queryToTest.sql" or "queryToTest.sql"

or even if we keep it the repositoryRoot should be relative, so instead of "C:\\dev\\jarvis" it would be "../../." etc

my aim is to get rid of _EVERY_ absolute path
___
*[examples/sample_volczi/terraform/main.tf, line 4 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoZs8z2diEg-EZYepO:-MxoZs8z2diEg-EZYepP:b-3wmh1l) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_volczi/terraform/main.tf#L4)):*
> ```HCL
> }
> 
> resource "google_bigquery_dataset" "dataset" {
> ```

fyi another cleanup task

at this point I think using `CREATE SCHEMA` ( https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_schema_statement  ) and `CREATE TABLE` ( https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_statement ) etc seems more straightforward and part of the normal flow compared to a terraform that has to be applied totally independent of the flow

also it can benefit from the templating we already have (project, etc)
___
*[examples/sample_volczi/volcziTest/case1/pre/volcziTest.sql, line 1 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoUwEqC-GbI94uvyzD:-MxoUwEqC-GbI94uvyzE:b-9h510o) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_volczi/volcziTest/case1/pre/volcziTest.sql#L1)):*
> ```TSQL
> DELETE FROM `{{project}}.jarvis_sample_volczi.car` WHERE 1 = 1;
> ```

was the issue created for the wrong order if TRUNCATE is used?
___
*[src/test/java/ai/aliz/talendtestrunner/actionConfig/AssertActionConfigTest.java, line 16 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoS7dmBiSt-2Ozd26g:-MxoS7dn-MLH5XRRvUtg:b9shjm3) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/src/test/java/ai/aliz/talendtestrunner/actionConfig/AssertActionConfigTest.java#L16)):*
> ```Java
> import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
> 
> import ai.aliz.jarvis.jarvisconfig.AssertActionConfig;
> ```

shouldn't this be `ai.aliz.jarvis.config.`, seems to make more sense?
___
*[examples/sample_tests/test_sql/jarvisTestSuite.json, line 1 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoVFVc4L6otZ4T4e3e:-MxoVFVc4L6otZ4T4e3f:b-ki9bie) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_tests/test_sql/jarvisTestSuite.json#L1)):*
> ```JSON
> {
> ```

we have more testSuite.json files, shouldn't they be also renamed?

**Review by gaborvolczer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45)* status: all files reviewed, 3 unresolved discussions (waiting on @nbali)

___
*[examples/sample_volczi/contexts.json, line 12 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoWD7-4Dan3riP64ov:-Mxs0ssP29iDYanz7tME:b-z70mv5) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_volczi/contexts.json#L12)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

fyi this something I really wanna get rid of soon :D I mean the files should be all referenced as relative paths, and the parameter provided (the context.json or the suite.json) to the app should determine the "repositoryRoot"

so there would be no "local" here

and "queryPath" would be "volcziTest/queryToTest.sql" or "queryToTest.sql"

or even if we keep it the repositoryRoot should be relative, so instead of "C:\\dev\\jarvis" it would be "../../." etc

my aim is to get rid of _EVERY_ absolute path


</blockquote></details>

Is it ok for you if I add this to the checklist on the ticket so the renaming subtask can proceed?
___
*[examples/sample_volczi/terraform/main.tf, line 4 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoZs8z2diEg-EZYepO:-Mxs0ci29TP5YgAmRk0U:b-z70mv5) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_volczi/terraform/main.tf#L4)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

fyi another cleanup task

at this point I think using `CREATE SCHEMA` ( https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_schema_statement  ) and `CREATE TABLE` ( https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_statement ) etc seems more straightforward and part of the normal flow compared to a terraform that has to be applied totally independent of the flow

also it can benefit from the templating we already have (project, etc)
</blockquote></details>

Is it ok for you if I add this to the checklist on the ticket so the renaming subtask can proceed?
___
*[examples/sample_volczi/volcziTest/case1/pre/volcziTest.sql, line 1 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoUwEqC-GbI94uvyzD:-MxrzoU004IbUpHbb-8M:b-1jaquq) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_volczi/volcziTest/case1/pre/volcziTest.sql#L1)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

was the issue created for the wrong order if TRUNCATE is used?
</blockquote></details>

yep I tested it again, sometimes failed sometimes not. It should be checked.

Is it ok for you if I add this to the checklist on the ticket so the renaming subtask can proceed?
___
*[src/test/java/ai/aliz/talendtestrunner/actionConfig/AssertActionConfigTest.java, line 16 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoS7dmBiSt-2Ozd26g:-Mxs0GVq6Xj5RfQjfloA:bdg2vx8) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/src/test/java/ai/aliz/talendtestrunner/actionConfig/AssertActionConfigTest.java#L16)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

shouldn't this be `ai.aliz.jarvis.config.`, seems to make more sense?
</blockquote></details>

Fine by me, and then what about JarvisConfigloader? Rename it to ConfigLoader?
___
*[examples/sample_tests/test_sql/jarvisTestSuite.json, line 1 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoVFVc4L6otZ4T4e3e:-Mxs09FIAiWB3bUQcQtR:b-xxcdwj) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_tests/test_sql/jarvisTestSuite.json#L1)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

we have more testSuite.json files, shouldn't they be also renamed?
</blockquote></details>

Where?

**Review by gaborvolczer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45)* status: 28 of 73 files reviewed, 3 unresolved discussions (waiting on @nbali)

___
*[src/test/java/ai/aliz/talendtestrunner/actionConfig/AssertActionConfigTest.java, line 16 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoS7dmBiSt-2Ozd26g:-Mxs5HR5EGsaRoA8E9vb:bzao0sg) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/src/test/java/ai/aliz/talendtestrunner/actionConfig/AssertActionConfigTest.java#L16)):*
<details><summary><i>Previously, gaborvolczer wrote…</i></summary><blockquote>

Fine by me, and then what about JarvisConfigloader? Rename it to ConfigLoader?
</blockquote></details>

renamed both
___
*[examples/sample_tests/test_sql/jarvisTestSuite.json, line 1 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoVFVc4L6otZ4T4e3e:-Mxs5Bgy-28nX1lH00lo:b-f7jkmi) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_tests/test_sql/jarvisTestSuite.json#L1)):*
<details><summary><i>Previously, gaborvolczer wrote…</i></summary><blockquote>

Where?
</blockquote></details>

I renamed a few more in test and README.

**Review by gaborvolczer — COMMENTED** [review]
@nbali I did some cleanup. Now there are no more dependency on the remaining 3 taledtestrunner... packages from jarvis packages.

I'm not sure if we should even go further with this as I would not fix any talend functionality now.

> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45#-:-MxsSJfQBTmOnMWJhJn_:bmcj784)* status: 22 of 79 files reviewed, 3 unresolved discussions (waiting on @nbali)

**Review by nbali — CHANGES_REQUESTED** [review]
@gaborvolczer well those aren't ONLY talend, but yeah if they aren't needed for bigquery - for now - I'm fine with this

> Reviewed 45 of 45 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 7 of 7 files at r7, 1 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45#-:-MxtGx1S7y0RUFDBY8dh:b-5i3ftf)* status: 67 of 79 files reviewed, 4 unresolved discussions (waiting on @gaborvolczer and @nbali)

___
*[README.MD, line 353 at r4](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxtBSrK7DrNIzIngUVh:-MxtBSrK7DrNIzIngUVi:bhi2qs2) ([raw file](https://github.com/aliz-ai/jarvis/blob/407429d6008f3c8c3f7a0affad899312c54cf397/README.MD#L353)):*
> ```
>     * test_case2
>     * jarvisTestSuite.json
> 3. one or more .sql file somewhere in the project (jarvisTestSuit.json queryPath) to make Bq table modification(s).
> ```

there is a typo (missing E) in all of these
___
*[examples/sample_volczi/contexts.json, line 12 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoWD7-4Dan3riP64ov:-MxtHDqr1OIVlLKf0ZA-:b-z15asw) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_volczi/contexts.json#L12)):*
<details><summary><i>Previously, gaborvolczer wrote…</i></summary><blockquote>

Is it ok for you if I add this to the checklist on the ticket so the renaming subtask can proceed?
</blockquote></details>

yeah it's not scope of this issue/PR, hence the FYI just wanted to give you context what also has to be done that is a serious problem with usability
___
*[examples/sample_volczi/terraform/main.tf, line 4 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoZs8z2diEg-EZYepO:-MxtHSmZ0X4VMkukfcSL:b-m2a6jh) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_volczi/terraform/main.tf#L4)):*
<details><summary><i>Previously, gaborvolczer wrote…</i></summary><blockquote>

Is it ok for you if I add this to the checklist on the ticket so the renaming subtask can proceed?
</blockquote></details>

"yeah it's not scope of this issue/PR, hence the FYI just wanted to give you context what also has to be done..."
___
*[examples/sample_volczi/volcziTest/case1/pre/volcziTest.sql, line 1 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoUwEqC-GbI94uvyzD:-MxtMF895q4r39rkIgZi:b-1d8wak) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_volczi/volcziTest/case1/pre/volcziTest.sql#L1)):*
<details><summary><i>Previously, gaborvolczer wrote…</i></summary><blockquote>

yep I tested it again, sometimes failed sometimes not. It should be checked.

Is it ok for you if I add this to the checklist on the ticket so the renaming subtask can proceed?
</blockquote></details>


right now this causing the order change, but IMO concurrent execution is the issue, we should get rid of eventually, there is no telling if someone wants to do serial execution or not

... but sure, not scope of this issue, just a reminder
___
*[src/main/java/ai/aliz/jarvis/JarvisApplication.java, line 18 at r4](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxtCbJn8N6J7Hx_gCpa:-MxtCbJo0Dh7eLSNhSDZ:b-735us1) ([raw file](https://github.com/aliz-ai/jarvis/blob/407429d6008f3c8c3f7a0affad899312c54cf397/src/main/java/ai/aliz/jarvis/JarvisApplication.java#L18)):*
> ```Java
>     
>     @Autowired
>     private ConfigLoader configLoader;
> ```

fyi I was fine with `JarvisConfigLoader` - but I'm also fine with `ConfigLoader` - my main concert was the package name `jarvis.jarvisconfig`
___
*[src/test/java/ai/aliz/talendtestrunner/service/BigQueryExecutorTest.java, line 60 at r5](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxtFNEJ3hpTwjvOR-mV:-MxtFNEJ3hpTwjvOR-mW:b-5xaxbf) ([raw file](https://github.com/aliz-ai/jarvis/blob/e7c1e50ddcff037676fe6769e6ac8de51112b248/src/test/java/ai/aliz/talendtestrunner/service/BigQueryExecutorTest.java#L60)):*
> ```Java
>         TableResult tableResult = getTableResult();
>         Mockito.when(bigQuery.query(Mockito.any())).thenReturn(tableResult);
>         Mockito.when(bigQueryService.createBigQueryClient(Mockito.any())).thenReturn(bigQuery);
> ```

how the f*ck does this test even work :D I mean it has no mocking to bigquery that is actually being used

---
aahh lol it's ignored, wtf

anyway that removed bigquery service will be needed eventually when this test is being fixed

as discussed testing isn't part of this now, but add a TODO for the @Ignore 
___
*[examples/sample_tests/test_sql/jarvisTestSuite.json, line 1 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoVFVc4L6otZ4T4e3e:-MxtGJrYE1Y2tm2npfv5:b-4i1bwh) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_tests/test_sql/jarvisTestSuite.json#L1)):*
<details><summary><i>Previously, gaborvolczer wrote…</i></summary><blockquote>

I renamed a few more in test and README.
</blockquote></details>

I will keep this open so I can check at the very end -> it's needed because it seems the code is hardwired to look for that specific file name

**Review by gaborvolczer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45)* status: 64 of 79 files reviewed, 2 unresolved discussions (waiting on @gaborvolczer, @ignore, and @nbali)

___
*[src/test/java/ai/aliz/talendtestrunner/service/BigQueryExecutorTest.java, line 60 at r5](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxtFNEJ3hpTwjvOR-mV:-MxxH0Bk0eWZ24Q7ctFe:b-896fix) ([raw file](https://github.com/aliz-ai/jarvis/blob/e7c1e50ddcff037676fe6769e6ac8de51112b248/src/test/java/ai/aliz/talendtestrunner/service/BigQueryExecutorTest.java#L60)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

how the f*ck does this test even work :D I mean it has no mocking to bigquery that is actually being used

---
aahh lol it's ignored, wtf

anyway that removed bigquery service will be needed eventually when this test is being fixed

as discussed testing isn't part of this now, but add a TODO for the @Ignore 
</blockquote></details>

Done.



_Code quote:_
```Java
BigQueryService 
```

**Review by gaborvolczer — COMMENTED** [review]
I would also rename the tests as we have TestXyz and XyzTest. Should we choose the first one? 

> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45#-:-MxxIkMrBT5mSBWXgmP2:b-yna7nb)* status: 64 of 79 files reviewed, 2 unresolved discussions (waiting on @gaborvolczer, @ignore, and @nbali)

**Review by nbali — CHANGES_REQUESTED** [review]
I would say yes. TestX is better than XTest

> Reviewed 4 of 4 files at r8, 4 of 5 files at r9, 2 of 2 files at r10, 3 of 3 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45#-:-MyGxI3B7aAc1ox-a_cI:bxfkwyk)* status: all files reviewed, 5 unresolved discussions (waiting on @gaborvolczer)

___
*[examples/sample_volczi/volcziTest/case1/pre/volcziTest.sql, line 1 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoUwEqC-GbI94uvyzD:-MyGzjJK6ebC-J52r8B8:b-inqk61) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_volczi/volcziTest/case1/pre/volcziTest.sql#L1)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>


right now this causing the order change, but IMO concurrent execution is the issue, we should get rid of eventually, there is no telling if someone wants to do serial execution or not

... but sure, not scope of this issue, just a reminder

</blockquote></details>

I assume you ACK-ed this because you added this to your TODO list.
___
*[src/main/java/ai/aliz/talendtestrunner/config/RetryConfig.java, line 15 at r11](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MyGyS-k58sO-id9eY_8:-MyGyS-k58sO-id9eY_9:blb0bml) ([raw file](https://github.com/aliz-ai/jarvis/blob/991e0e3f6974ba354d00762f4e2ac75b5247550a/src/main/java/ai/aliz/talendtestrunner/config/RetryConfig.java#L15)):*
> ```Java
> 
> @Configuration
> public class RetryConfig {
> ```

note to self, used by talend code, check if needed
___
*[src/main/java/ai/aliz/talendtestrunner/service/ExecutionActionService.java, line 19 at r9](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MyGyj_t96Ra1xiFgvEo:-MyGyj_t96Ra1xiFgvEp:b-vwussi) ([raw file](https://github.com/aliz-ai/jarvis/blob/202bd8896fbcc20c7d49a6c685976aa8b2a2cded/src/main/java/ai/aliz/talendtestrunner/service/ExecutionActionService.java#L19)):*
> ```Java
>         RetryTemplate retryTemplate = retryConfig.retryTemplate(retryConfig.retryPolicy(), retryConfig.backOffPolicy());
>         TalendApiService talendApiService = new TalendApiService(new PlaceholderResolver(), new RestTemplate(), retryTemplate);
>         talendApiService.executeTask(taskName, contextLoader.getContext("TalendAPI"));
> ```

well this is talend related code, shouldn't we keep that?
___
*[src/test/java/ai/aliz/talendtestrunner/util/PlaceholderResolverTest.java, line 11 at r9](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MyGwlQMBwxVyP2AWFkF:-MyGwlQMBwxVyP2AWFkG:b9kgm0m) ([raw file](https://github.com/aliz-ai/jarvis/blob/202bd8896fbcc20c7d49a6c685976aa8b2a2cded/src/test/java/ai/aliz/talendtestrunner/util/PlaceholderResolverTest.java#L11)):*
> ```Java
> import java.util.Map;
> 
> import ai.aliz.jarvis.util.PlaceholderResolver;
> ```

seems like this test should be moved to the 'proper' package (ai.aliz.jarvis.util)
___
*[src/main/java/ai/aliz/talendtestrunner/service/JarvisRunnerService.java, line 19 at r9](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MyGzFn-7K7ybMi4bN-i:-MyGzFn-7K7ybMi4bN-j:b8s0olx) ([raw file](https://github.com/aliz-ai/jarvis/blob/202bd8896fbcc20c7d49a6c685976aa8b2a2cded/src/main/java/ai/aliz/talendtestrunner/service/JarvisRunnerService.java#L19)):*
> ```Java
> @AllArgsConstructor
> @Slf4j
> public class JarvisRunnerService {
> ```

isn't this a core class of the talend functionality? i mean runTalendJob, was it moved somewhere already?

**Review by gaborvolczer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45)* status: 74 of 79 files reviewed, 5 unresolved discussions (waiting on @gaborvolczer and @nbali)

___
*[examples/sample_volczi/contexts.json, line 12 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoWD7-4Dan3riP64ov:-MyHqHB92Z7KIzGSp-Gn:b-bojblj) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_volczi/contexts.json#L12)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

yeah it's not scope of this issue/PR, hence the FYI just wanted to give you context what also has to be done that is a serious problem with usability
</blockquote></details>

https://github.com/aliz-ai/jarvis/issues/47
___
*[examples/sample_volczi/terraform/main.tf, line 4 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoZs8z2diEg-EZYepO:-MyHqlRQ0esndz_eVLuq:b-bojbli) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_volczi/terraform/main.tf#L4)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

"yeah it's not scope of this issue/PR, hence the FYI just wanted to give you context what also has to be done..."
</blockquote></details>

https://github.com/aliz-ai/jarvis/issues/48
___
*[examples/sample_volczi/volcziTest/case1/pre/volcziTest.sql, line 1 at r3](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MxoUwEqC-GbI94uvyzD:-MyHpB0PB36NuANmyEPI:b-bojblk) ([raw file](https://github.com/aliz-ai/jarvis/blob/829863af82c3dcfbd287ec4282eece1b5a248412/examples/sample_volczi/volcziTest/case1/pre/volcziTest.sql#L1)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

I assume you ACK-ed this because you added this to your TODO list.
</blockquote></details>

https://github.com/aliz-ai/jarvis/issues/46
___
*[src/main/java/ai/aliz/talendtestrunner/service/ExecutionActionService.java, line 19 at r9](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MyGyj_t96Ra1xiFgvEo:-MyHt3o27J9yThUYtMgY:bvth56w) ([raw file](https://github.com/aliz-ai/jarvis/blob/202bd8896fbcc20c7d49a6c685976aa8b2a2cded/src/main/java/ai/aliz/talendtestrunner/service/ExecutionActionService.java#L19)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

well this is talend related code, shouldn't we keep that?
</blockquote></details>

reverted
___
*[src/test/java/ai/aliz/talendtestrunner/util/PlaceholderResolverTest.java, line 11 at r9](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MyGwlQMBwxVyP2AWFkF:-MyHsy0t2lo5GczmDvHb:b-896fix) ([raw file](https://github.com/aliz-ai/jarvis/blob/202bd8896fbcc20c7d49a6c685976aa8b2a2cded/src/test/java/ai/aliz/talendtestrunner/util/PlaceholderResolverTest.java#L11)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

seems like this test should be moved to the 'proper' package (ai.aliz.jarvis.util)
</blockquote></details>

Done.
___
*[src/main/java/ai/aliz/talendtestrunner/config/RetryConfig.java, line 15 at r11](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MyGyS-k58sO-id9eY_8:-MyHt0Fd8rMcsLVPvOE_:bvth56w) ([raw file](https://github.com/aliz-ai/jarvis/blob/991e0e3f6974ba354d00762f4e2ac75b5247550a/src/main/java/ai/aliz/talendtestrunner/config/RetryConfig.java#L15)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

note to self, used by talend code, check if needed
</blockquote></details>

reverted
___
*[src/main/java/ai/aliz/talendtestrunner/service/JarvisRunnerService.java, line 19 at r9](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MyGzFn-7K7ybMi4bN-i:-MyHsXBX-SamKNuSDCgk:brl5e1k) ([raw file](https://github.com/aliz-ai/jarvis/blob/202bd8896fbcc20c7d49a6c685976aa8b2a2cded/src/main/java/ai/aliz/talendtestrunner/service/JarvisRunnerService.java#L19)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

isn't this a core class of the talend functionality? i mean runTalendJob, was it moved somewhere already?
</blockquote></details>

reverted

Is it ok to keep it as it is? I mean I would not fix it and without fixing it would be hard to include the functionality into the new service.

**Review by gaborvolczer — COMMENTED** [review]
fixed

> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45#-:-MyHuDa19ygDVVwGwmAE:b-7ql1td)* status: 72 of 81 files reviewed, 5 unresolved discussions (waiting on @gaborvolczer and @nbali)

**Review by nbali — COMMENTED** [review]
> Reviewed 3 of 3 files at r13, 1 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45)* status: 76 of 81 files reviewed, 2 unresolved discussions (waiting on @gaborvolczer and @nbali)

___
*[src/main/java/ai/aliz/talendtestrunner/service/JarvisRunnerService.java, line 19 at r9](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MyGzFn-7K7ybMi4bN-i:-MyK9YA80Cla3nnv8r38:b-mgf37b) ([raw file](https://github.com/aliz-ai/jarvis/blob/202bd8896fbcc20c7d49a6c685976aa8b2a2cded/src/main/java/ai/aliz/talendtestrunner/service/JarvisRunnerService.java#L19)):*
<details><summary><i>Previously, gaborvolczer wrote…</i></summary><blockquote>

reverted

Is it ok to keep it as it is? I mean I would not fix it and without fixing it would be hard to include the functionality into the new service.
</blockquote></details>

as we discussed talend is out-of-scope for now, until it brakes something just keep it

**Review by nbali — COMMENTED** [review]
> Reviewed 1 of 1 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45)* status: 80 of 81 files reviewed, 1 unresolved discussion (waiting on @gaborvolczer and @nbali)

**Review by nbali — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45)* status: all files reviewed, 2 unresolved discussions (waiting on @gaborvolczer)

___
*[src/test/java/ai/aliz/talendtestrunner/IntegrationTestRunner.java, line 73 at r10](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MyKAebm5jJK3QaZD_D5:-MyKAebm5jJK3QaZD_D6:b967tra) ([raw file](https://github.com/aliz-ai/jarvis/blob/ff5681385dbe7b9393ea7c91aeff2c3c3cb16c96/src/test/java/ai/aliz/talendtestrunner/IntegrationTestRunner.java#L73)):*
> ```Java
>     public void runJarvisTestCase() throws Exception {
> //        contextLoader.parseContext(contextPath);
>         jarvisRunnerService.runJarvisTestCase(jarvisTestCase);
> ```

what does this test class do now? (I'm curious about the old and the new runner service as well)

**Review by gaborvolczer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45)* status: all files reviewed, 2 unresolved discussions (waiting on @gaborvolczer and @nbali)

___
*[src/test/java/ai/aliz/talendtestrunner/IntegrationTestRunner.java, line 73 at r10](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MyKAebm5jJK3QaZD_D5:-MyLxecH4OcgCEi7_wMG:b-n3o4ei) ([raw file](https://github.com/aliz-ai/jarvis/blob/ff5681385dbe7b9393ea7c91aeff2c3c3cb16c96/src/test/java/ai/aliz/talendtestrunner/IntegrationTestRunner.java#L73)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

what does this test class do now? (I'm curious about the old and the new runner service as well)
</blockquote></details>

Throws an NPE in line 51.

I think it is needed for the "integration" tests. I never did the proper setup for them so they are failing for me

**Review by nbali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45)* status: all files reviewed, 1 unresolved discussion (waiting on @gaborvolczer)

___
*[src/test/java/ai/aliz/talendtestrunner/IntegrationTestRunner.java, line 73 at r10](https://reviewable.io/reviews/aliz-ai/jarvis/45#-MyKAebm5jJK3QaZD_D5:-MyNAI1ICbQFptBm-zXn:brrg6ft) ([raw file](https://github.com/aliz-ai/jarvis/blob/ff5681385dbe7b9393ea7c91aeff2c3c3cb16c96/src/test/java/ai/aliz/talendtestrunner/IntegrationTestRunner.java#L73)):*
<details><summary><i>Previously, gaborvolczer wrote…</i></summary><blockquote>

Throws an NPE in line 51.

I think it is needed for the "integration" tests. I never did the proper setup for them so they are failing for me



</blockquote></details>

yeah, it's not being picked up by unit tests as it's not matching the class name pattern, so out-of-scope later when we do testing

**Review by nbali — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45)* status: all files reviewed, 1 unresolved discussion (waiting on @gaborvolczer)

**Review by nbali — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/jarvis/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaborvolczer)

**Pull request merged**
